
import type { Song } from "$lib/types/types";

const songs:Song[] = [
    { title: "ÇÖP", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "ACI VERİYOR", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "AYRILMAM", tone: "Cm", modality: "Minor", lyrics: "", links: [] },
    { title: "İSTER VUR İSTER OKŞA", tone: "CM", modality: "Minor", lyrics: "", links: [] },
    { title: "KIŞ GÜNEŞİ", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "PEMBE DİZİ", tone: "Cm", modality: "Minor", lyrics: "", links: [] },
    { title: "İKİMİZE BİRDEN", tone: "Bm", modality: "Minor", lyrics: "", links: [] },
    { title: "YA SONRA", tone: "Bm", modality: "Minor", lyrics: "", links: [] },
    { title: "GİDENLERDEN", tone: "Dm", modality: "Minor", lyrics: "", links: [] },
    { title: "JEST OLDUM", tone: "Dm", modality: "Minor", lyrics: "", links: [] },
    { title: "ÇALKALA HADİ ADAMIM", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "AŞK LAZIM", tone: "Bm", modality: "Minor", lyrics: "", links: [] },
    { title: "ÇOK TATLISIN ÇOK", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "TAVLA", tone: "GM", modality: "Minor", lyrics: "", links: [] },
    { title: "KANDIRDIM", tone: "Bm", modality: "Minor", lyrics: "", links: [] },
    { title: "ŞARKI", tone: "Am", modality: "Kurdi", lyrics: "", links: [] },
    { title: "İNADI BIRAK YANIMA YANASIVER", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "YUZSUZ YUREK", tone: "Bm", modality: "Minor", lyrics: "", links: [] },
    { title: "İBRETİ ALEM", tone: "Cm", modality: "Minor", lyrics: "", links: [] },
    { title: "YAŞAMAK VARYA", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "DELİ ET BENİ", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "ALLAHIM NEYDI GUNAHIM", tone: "Gm", modality: "Kurdi", lyrics: "", links: [] },
    { title: "Yalan", tone: "Am", modality: "Kurdi", lyrics: "", links: [] },
    { title: "Duyanlara", tone: "A", modality: "hicaz", lyrics: "", links: [] },
    { title: "Kapanmaz yarayım", tone: "A", modality: "hicaz", lyrics: "", links: [] },
    { title: "Ama don desem", tone: "F#m", modality: "Kurdi", lyrics: "", links: [] },
    { title: "Telefon", tone: "F#m", modality: "Kurdi", lyrics: "", links: [] },
    { title: "Olmaz kenan", tone: "Dm", modality: "Minor", lyrics: "", links: [] },
    { title: "Ömrümün geri kalanı", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Sigara", tone: "Em", modality: "nihavet", lyrics: "", links: [] },
    { title: "Adırma deli gönlüm", tone: "Cm", modality: "Minor", lyrics: "", links: [] },
    { title: "Sen yeter ki sev", tone: "Cm", modality: "Minor", lyrics: "", links: [] },
    { title: "Aşkın Ateşi", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Deli Bile", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Sen Yoluna", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Kapına köleyim", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Kırmızı", tone: "Em", modality: "Minor", lyrics: "", links: [] },
    { title: "Tutamıyorum Zamanı", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "Benimle Oynama", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "Kınalı Bebek", tone: "Am", modality: "Minor", lyrics: "", links: [] },
    { title: "Üzülme Boş Yere", tone: "Am", modality: "Kurdi", lyrics: "", links: [] },
    { title: "Seninle Başım Dertte", tone: "Dm", modality: "Minor", lyrics: "", links: [] },
    { title: "Bambaşka Biri", tone: "Dm", modality: "Minor", lyrics: "", links: [] },
    { title: "Değer mi hiç?", tone: "Dm", modality: "Minor", lyrics: "", links: [] }
]

export default songs;